### ISSUE TITLE
open-variant | does not iterate in folder in versions >= `v0.6.17`

### ISSUE THREAD

**Issue by FedericaBrando** [bbglab/openvariant#12]
As the title says.

### command

```sh
openvar groupby /workspace/projects/intogen_plus/fixdatasets-20220321/intogen-plus/test/pipeline/ -g  "DATASET" --show --header 
```

#### from v 0.7.5 to v. 0.6.18

it doesn't give any output. It does not iterate in the folder.

#### v 0.6.17

output:

```sh
Traceback (most recent call last):
  File "/home/fbrando/miniconda3/envs/intogenHM/bin/openvar", line 5, in <module>
    from openvariant.commands.openvar import openvar
  File "/home/fbrando/miniconda3/envs/intogenHM/lib/python3.7/site-packages/openvariant/__init__.py", line 4, in <module>
    from openvariant.tasks import cat, count, group_by
  File "/home/fbrando/miniconda3/envs/intogenHM/lib/python3.7/site-packages/openvariant/tasks/__init__.py", line 1, in <module>
    from .cat import cat
  File "/home/fbrando/miniconda3/envs/intogenHM/lib/python3.7/site-packages/openvariant/tasks/cat.py", line 9, in <module>
    from openvariant.find_files.find_files import find_files
ImportError: cannot import name 'find_files' from 'openvariant.find_files.find_files' (/home/fbrando/miniconda3/envs/intogenHM/lib/python3.7/site-packages/openvariant/find_files/find_files.py)
```

#### v 0.6.16

The output is the one expected.

**Comment by CarlosLopezElorduy** [comment]
I created a [pull request](https://github.com/bbglab/openvariant/pull/13) with a quick fix (although pretty sure it might break other things) so that David can tackle the issue from there.

If you still want to use the groupby function, a workaround is to specify either the path where the file is located or the path of the file itself.

**Comment by FedericaBrando** [comment]
Thanks Carlos!

The problem is it is the very first step in intogen and we point to a parent folder to reach every dataset. 

I solved it by using the v.0.6.16 for now.

**Comment by FedericaBrando** [comment]
I think part of the problem is that open-variants does not iterate in the `basepath` since the generator [`_find_files`](https://github.com/bbglab/openvariant/blob/v0.7.5-alpha/openvariant/find_files/find_files.py#L52) is not properly called at line [86](https://github.com/bbglab/openvariant/blob/v0.7.5-alpha/openvariant/find_files/find_files.py#L86). 

As I understood, since it is a generator it needs to be called in a loop, otherwise it would not use the function. 

something like: 
```diff

def findfiles(base_path: str, annotation_path: str or None = None) -> Generator[str, Annotation, None]:
    """Get each file and its proper annotation object.

    Parameters
    ----------
    base_path : srt
        Base path of input folder/file.
    annotation_path : str or None
        Path of annotation file.

    Yields
    -------
    str
        Input file's name.
    Annotation
        The proper schema of each input file.
    """
    annotation, fix = (Annotation(annotation_path), True) if annotation_path is not None else (None, False)
+   for f, a in _find_files(base_path, annotation, fix):
+         yield f, a
-   return _find_files(base_path, annotation, fix)
```

@dmartmillan

**Comment by FedericaBrando** [comment]
Moreover, I think there is an indentation that shouldn't be there. 
In fact, when an annotation path is not present, the `else` condition in [`_find_files`](https://github.com/bbglab/openvariant/blob/v0.7.5-alpha/openvariant/find_files/find_files.py#L57) has inside a for loop that calls the `Annotation()` . Inside the for loop there is another for loop that call the `_scan_files()` generator. If I am not mistaken the second for loop should be outside of the first one:

```diff
def _find_files(base_path: str, annotation: Annotation or None, fix: bool) -> Generator[str, Annotation, None]:
    """Recursive exploration from a base path distinct if there's a fix annotation or no"""
    if not fix:
        if isfile(base_path):
            annotation_path = dirname(base_path)
        else:
            annotation_path = base_path
        for annotation_file in glob.iglob(join(annotation_path, "*.{}".format(ANNOTATION_EXTENSION))):
            annotation = Annotation(annotation_file)

+       for f, a in _scan_files(base_path, annotation, fix):
+           yield f, a
-            for f, a in _scan_files(base_path, annotation, fix):
-                yield f, a
    else:
        for f, a in _scan_files(base_path, annotation, fix):
            yield f, a
```
