### ISSUE TITLE
open-variant |  update in PyPi in a new version

### ISSUE THREAD

**Issue by FedericaBrando** [bbglab/openvariant#16]
new version: 

0.7.5 --> 0.7.6

- [x] update master setup.py
- [x] update pipy

**Comment by FedericaBrando** [comment]
I don't have permission to merge on main branch.

**Comment by dmartmillan** [comment]
@FedericaBrando I added you as an Admin. Try now :)

**Comment by dmartmillan** [comment]
But I think that needs a review... Let me check!

**Comment by FedericaBrando** [comment]
Hi @dmartmillan, I manage to merge the PR, bypassing the reviewer request :) Thanks a lot!
