### ISSUE TITLE
Add output parameter on openvar commands

### ISSUE THREAD

**Issue by dmartmillan** [bbglab/openvariant#4]
Add a new flag `-o` `--output` on each task command to save the result on a specific path.

The flag is currently implemented in the `develop` branch.

**Comment by CarlosLopezElorduy** [comment]
Added `-o` `--output` flag:

- [ ] cat
- [ ] count
- [ ] groupby

**Comment by CarlosLopezElorduy** [comment]
@dmartmillan Can you test if it works fine?

**Comment by dmartmillan** [comment]
### Test successful

The new parameter (--output, -o) was tested on the 3 different commands and it worked fine.
